server:
  port: 9412
spring:
  application:
    name: mall-trace
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ag_zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  sleuth:
    enabled: false
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 #将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
  rabbitmq:
    addresses: localhost
    port: 5672
    username:
    password:
    virtual-host: sleuth
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      enabled: true
      discovery:
        service-name: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        register: true
        enabled: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:8764