server:
  port: 8764
spring:
  application:
    name: mall-monitor
  cloud:
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true #window 开启telnet
        register: true
        healthCheckPath: ${management.server.servlet.context-path}/health
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        tags: mall-monitor
        service-name: ${spring.application.name}
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  server:
#    servlet:
#      context-path: /
#    ssl:
#      enabled: false
#  endpoint:
#    health:
#      show-details: always
