spring:
  application:
    name: mall-uid
server:
  port: 7777
uid:
  datacenter: 2
  port: 9999 # thrift
  zookeeper:
    servers:
      - localhost
      - localhost2
    port: 2181
    root: "/ds-mall"
    persistent: "/pseq"
    ephemeral: "/eseq"
    sessionTimeoutMs: 20000
    connectionTimeoutMs: 15000
    retryTimes: 20
    retryIntervalMs: 1000
    retryIntervalceilingMs: 30000
    heartbeatIntervalMs: 3000
    averageTimestampThreshold: 5000
