server:
  port: 8888
spring:
  application:
    name: auth-server
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      enabled: true
      discovery:
        service-name: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        register: true
        enabled: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:8764
